diary/api/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework.authtoken import views as authtoken_views
from api import views

router = routers.DefaultRouter()
router.register(r'stories', views.StoryViewSet)
router.register(r'summaries', views.StorySummaryViewSet, basename='story-summary')
router.register(r'authors', views.AuthorViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('auth/api-token/', authtoken_views.obtain_auth_token, name='api-token'),
    path('auth/register/', views.create_user, name='api-register-user'),
    path('auth/', include('rest_framework.urls', namespace='rest_framework')),
]

diary/authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'
urlpatterns = [
    path('my-pseudonyms/', views.MyPseudonyms.as_view(), name='my-pseudonyms'),
    path('create/', views.Create.as_view(), name='create'),
    path('explain/', views.Explain.as_view(), name='explain'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),
]

diary/diary/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name="teaser.html")),
    path('admin/', admin.site.urls),
    path('stories/', include('stories.urls')),
    path('licenses/', include('licenses.urls')),
    path('martor/', include('martor.urls')),
    path('accounts/', include('userena.urls')),
    path('authors/', include('authors.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

diary/stories/urls.py
from django.urls import path
from . import views

app_name = 'stories'
urlpatterns = [
    path('', views.Recent.as_view(), name='recent'),
    path('list-by-author/<int:pk>/', views.ByAuthor.as_view(), name='list-by-author'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('create/', views.Create.as_view(), name='create'),
    path('read/<int:pk>/', views.Read.as_view(), name='read'),
]

diary/stories/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext as _
from django.utils.safestring import SafeString

from martor.models import MartorField

from stories.utils import markdownify

# Create your models here.

class StoryQuerySet(models.QuerySet):
    pass


class StoryManager(models.Manager):
    def get_queryset(self):
        return StoryQuerySet(self.model, using=self._db)

    def recent(self):
        """ Order the list of visible Entries by their published date (descending) """
        return self.published()

    def published(self, **kwargs):
        """ Return a QS of all published articles that have not been hidden """
        return (self.filter(hidden_at=None, **kwargs)
                .exclude(published_at__isnull=True)
                .order_by('-published_at'))

    def by_author(self, author):
        """ Return the recent list of stories by this author """
        return self.recent().filter(author=author)

    def inspired(self, inspiration):
        """ Return a queryset of the list of stories inspired by this story """
        return self.published(inspired_by=inspiration)

    def next_chapter(self, story):
        """ A story by the same author that comes after this story is tne
             next_chapter of this story """
        return self.published(preceded_by=story, author=story.author)

    def drafts(self, user):
        """ Return a queryset of drafts written by this user so they can finish them
              and get them published. """
        return self.filter(published_at__isnull=True, author__user=user)


class Story(models.Model):
    """ Holds a single story's content and relationships to other stories """
    author = models.ForeignKey('authors.Author', verbose_name=_("Pseudonym"),
                               on_delete=models.PROTECT)
    title = models.CharField(max_length=64, null=False, blank=False)
    tagline = models.CharField(max_length=64, blank=True)
    text = MartorField(null=False, blank=False)

    # The preview used in the list view.  Autogenerated with possible override by the author
    teaser = models.TextField(blank=False, null=True, max_length=140)

    # The story behind the story.  (No, this should probably NOT be a separate story.)
    about = MartorField(blank=True)

    # Source of this story (if it was copied from somewhere else)
    source = models.URLField(blank=True)

    # This is the license under which the story is controlled
    license = models.ForeignKey('licenses.license', null=True, blank=True, on_delete=models.PROTECT)

    # This was published by the author on this date (None = draft/private)
    published_at = models.DateTimeField(default=None, null=True, blank=True, db_index=True)

    # This was hidden by an admin for questionable content
    hidden_at = models.DateTimeField(default=None, null=True, blank=True)

    # The author is writing this story because they were inspired_by the indicated story
    inspired_by = models.ForeignKey('self', default=None, null=True, blank=True,
                                    on_delete=models.PROTECT)

    # This story follows another story (like inspired_by, but more like a chapter2 situation)
    preceded_by = models.ForeignKey('self', default=None, null=True, blank=True,
                                    on_delete=models.PROTECT, related_name='previous_chapter')


    # Language the story is written in (so we can tell the browser in the HTTP headers and trigger
    #   translation prompting)
    language = models.CharField(_('language'),
                                max_length=5,
                                choices=settings.LANGUAGES,
                                default=settings.LANGUAGE_CODE[:2],
                                help_text=_('Story language.'))

    class Meta:
        verbose_name_plural = "stories"


    objects = StoryManager()

    def __str__(self):
        return self.full_title()

    def full_title(self):
        """ """
        return '%s: %s' % (self.title, self.tagline)

    def read_time(self):
        return _("Short read")

    def html(self):
        """ Return the html version of the markdown.  Wraps it as a SafeString so it will
              display without being escaped.  This should probably be done and cached somewhere
              and let this method do a lookup for the cached version.  An alternative would be to
              double the storage in the DB but that could mean having to update the whole  DB if we
              fix something about martor.  Storing this in a memcached instance would probably
              be better """
        # TODO: Store the results in memcached for speed
        return SafeString(markdownify(self.text))

    def next_chapter_id(self):
        """ The id of the story (with preceeded_by_id == self.id) by the same author
              is the next_chapter of this story. This is used by the serializers"""
        if not hasattr(self, '_next_chapter_id'):
            self._next_chapter_id = Story.objects.next_chapter(story=self).values_list('id', flat=True).first()
        return self._next_chapter_id

    def next_chapter(self):
        """ A story by the same author that comes after this story is tne
             next_chapter of this story.  This is used when formatting the story with a template. """
        if not hasattr(self, '_next_chapter'):
            self._next_chapter = Story.objects.next_chapter(story=self).first()
        return self._next_chapter

    def refresh_from_db(self, using=None, fields=None):
        """ Clear the extra pseudo fields we have added for next_chapter and next_chapter_id since Django
              doesn't know about them """
        if hasattr(self, '_next_chapter') and (not fields or '_next_chapter' in fields):
            del self._next_chapter
        if hasattr(self, '_next_chapter_id') and (not fields or '_next_chapter_id' in fields):
            del self._next_chapter_id

        return super(Story, self).refresh_from_db(using, fields)


class Flag(models.Model):
    """ When an entry is flagged, it gets one of these records"""
    HATE_SPEECH = 1
    SPAM = 2
    EXPLICIT = 3

    FLAG_CHOICES = (
        (HATE_SPEECH, _("Hate Speech")),
        (SPAM, _("Spam")),
        (EXPLICIT, _("Sexually Explicit")),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.PROTECT)
    entry = models.ForeignKey(Story, null=False, db_index=True, on_delete=models.PROTECT)
    flagged_at = models.DateTimeField(auto_now_add=True, null=False)
    reason = models.IntegerField(choices=FLAG_CHOICES, default=0)


class UpVotes(models.Model):
    """ When an entry is UpVoted, it gets one of these records"""
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.PROTECT)
    entry = models.ForeignKey(Story, null=False, db_index=True, on_delete=models.PROTECT)
    voted_at = models.DateTimeField(auto_now_add=True, null=False)


class DownVotes(models.Model):
    """ When an entry is DownVoted, it gets one of these records"""
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.PROTECT)
    entry = models.ForeignKey(Story, null=False, db_index=True, on_delete=models.PROTECT)
    voted_at = models.DateTimeField(auto_now_add=True, null=False)

diary/stories/forms.py
from django import forms
from django.utils import timezone
from django.utils.translation import gettext as _

from martor.fields import MartorFormField

from licenses.models import License
from stories.models import Story
from authors.models import Author

class PublishForm(forms.ModelForm):

    license = forms.ModelChoiceField(queryset=License.objects.active(), required=True)
    private = forms.BooleanField(required=False)

    class Meta:
        model = Story
        fields = ['teaser', 'author', 'license', 'private']
        
    
class RelatedByIdField(forms.ModelChoiceField):
    widget = forms.CheckboxInput

    def to_python(self, value):
        """ This is a boolean for yes/no, we need the related object if it is True """
        if value:
            return self.queryset.first()
        return None

class StoryForm(forms.ModelForm):
    """ Used to create or edit a story.  It picks up on inspired_by via 2 mechanisms """

    text = MartorFormField(label=_('Story'), required=True)
    author = forms.ModelChoiceField(label=_('Pseudonym'), queryset=None, required=True)
    private = forms.BooleanField(required=False)
    inspired_by = RelatedByIdField(required=False, queryset=None)
    preceded_by = RelatedByIdField(label=_("This story is preceded by"), required=False, queryset=None)

    class Meta:
        model = Story
        fields = ['author', 'preceded_by', 'title', 'tagline', 'text', 'inspired_by', 'private']

    def get_from_object_or_data(self, name):
        """ We can get a value for some fields from the initial, data or the instance and it 
              might be an int or an instance.  Hide all of that here."""
        if self.instance and getattr(self.instance, name):
            return getattr(self.instance, name).id
        else:
            value = self.initial.get(name, self.data.get(name, None))
            if value:
                if isinstance(value, Story):
                    return value.id
                else:
                    return int(value)

        return None
        
    def adjust_field(self, name):
        obj_id = self.get_from_object_or_data(name)
        if obj_id:
            self.fields[name].queryset = Story.objects.published(pk=obj_id)
        else:
            # The user cannot supply a value for these fields (only check the box)
            #   Remove the field if there is no value to check the box for
            del self.fields[name]
        

    def __init__(self, *args, user, **kwargs):
        super(StoryForm, self).__init__(*args, **kwargs)

        width = Story._meta.get_field('title').max_length
        self.fields['title'].widget.attrs['size'] = width
        self.fields['tagline'].widget.attrs['size'] = width
        self.fields['text'].widget.attrs['cols'] = width

        self.fields['author'].queryset = Author.objects.for_user(user)

        # These are optional fields that may or may not be present depending on 
        #   GET params or values in the instance.  Remove/adjust them depending
        #   on the data available.
        self.adjust_field('inspired_by')
        self.adjust_field('preceded_by')


    def save(self, commit=True):

        obj = super(StoryForm, self).save(commit=False)

        if self.cleaned_data['private']:
            obj.published_at = None
        elif not obj.published_at:
            obj.published_at = timezone.now()

        if commit:
            obj.save()
            self.save_m2m()
        return obj

diary/stories/views.py
import urllib

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, CreateView, ModelFormMixin
from django.urls import reverse
from django.utils.translation import gettext as _
from django.utils import timezone

from .models import Story
from authors.models import Author
from .forms import StoryForm, PublishForm

# Create your views here.

class Recent(ListView):
    """ List recent entries that have been published """

    def get_queryset(self):
        return Story.objects.recent()


class ByAuthor(ListView):
    """ List recent entries that have been published """

    def get_template_names(self):
        return ['stories/story-list-by-author.html']

    def get_queryset(self):
        return Story.objects.by_author(author=self.kwargs['pk'])

    def get_context_data(self):
        """ Not sure why the call arguments are empty like this, it should have an
             object_list and **kwargs, but those are throwing errors......"""
        context = super(ByAuthor, self).get_context_data()
        context['author'] = Author.objects.get(pk=self.kwargs['pk'])
        return context


class CommonStoryFormMixin(ModelFormMixin):

    model = Story
    form_class = StoryForm

    def get_field_from_request(self, name):
        """ Return the story that inspired this story or preceded this story,
              take that from the object, 
              or if creating a new story, from the GET params """
        _name = '_' + name
        if not hasattr(self, _name):
            setattr(self, _name, None)

            if self.object:
                setattr(self, _name, getattr(self.object, name))

            pk = self.request.GET.get(name, None)
            if pk:
                # This seems hacky as hell.....
                setattr(self, _name, Story.objects.published(pk=int(pk)).first())
            else:
                setattr(self, _name, None)

        return getattr(self, _name)



    def get_form_kwargs(self):
        """ The form needs the user to get the list of possible authors """
        kwargs = super(CommonStoryFormMixin, self).get_form_kwargs()
        kwargs['user'] = self.request.user

        return kwargs

    def get_success_url(self):
        return reverse('stories:read', kwargs={'pk': self.object.id})

    def get_initial(self):
        initial = super(CommonStoryFormMixin, self).get_initial()
        for key in ('inspired_by', 'preceded_by', 'author'):
            value = self.get_field_from_request(key)
            if value:
                initial[key] = value
        return initial

    def get_context_data(self, **kwargs):
        context = super(CommonStoryFormMixin, self).get_context_data(**kwargs)
        for key in ('inspired_by', 'preceded_by'):
            context[key] = self.get_field_from_request(key)
        return context


class Create(LoginRequiredMixin, CommonStoryFormMixin, CreateView):
    """ Create a new entry in the diary of life """

    def get(self, request, *args, **kwargs):
        has_pseudonyms = Author.objects.for_user(self.request.user).exists()

        if not has_pseudonyms:
            return HttpResponseRedirect(reverse('authors:explain')
                                        + '?' + urllib.parse.urlencode({
                                            'next': request.get_full_path()
                                        }))
        self.object = None
        return super(Create, self).get(request, *args, **kwargs)


class Edit(LoginRequiredMixin, CommonStoryFormMixin, UpdateView):
    """ Update an existing entry in the diary of life """
    pass

class Publish(LoginRequiredMixin, CommonStoryFormMixin, UpdateView):
    """ Publish a saved but as yet unpublished entry in the diary of life """
    form_class = PublishForm



class Read(DetailView):
    model = Story

    def get_object(self, queryset=None):
        obj = super(Read, self).get_object(queryset)

        if not obj.published_at and obj.author.user != self.request.user:
            obj.title = _("This entry is private")
            obj.text = _("This entry can only be read by it's author")

        if obj.hidden_at:
            obj.title = _("This entry is hidden")
            obj.text = _("This entry is not available for viewing by anyone")

        return obj

    def get_context_data(self, **kwargs):
        context = super(Read, self).get_context_data(**kwargs)
        context['inspired'] = Story.objects.inspired(inspiration=self.object)

        return context

diary/templates/stories/story-list-by-author.html
{% extends "base.html" %}
{% load static %}

{% block PageTitle %}
  Stories by: {{ author.name }} -- {{ block.super }}
{% endblock PageTitle %}

{% block content %}

<!-- Begin Featured ================================================== -->
<section class="featured-posts">
<div class="section-title">
        <h2><span>Stories written by {{ author.name }}</span></h2>
        <div class='bio'>{{ author.bio_html }}</div>
</div>
<div class="card-columns listfeaturedtag">

    {% for object in object_list %}
        <div class="card">
                <div class="row">
                        <div class="col-md-5 wrapthumbnail">
                                <a href="post.html">
                                        <div class="thumbnail" style="background-image:url({% static 'img/demopic/1.jpg' %});">
                                        </div>
                                </a>
                        </div>
                        <div class="col-md-7">
                            <a href="{% url "stories:read" pk=object.pk %}">
                                <div class="card-block">
                                    <h2 class="card-title">{{ object.title }}</h2>
                                    <h3 class="cart-tagline">{{ object.tagline }}</h3>
                                    <h4 class="card-text">{{ object.html|truncatechars_html:100 }}</h4>
                                    <div class="metafooter">
                                        <div class="wrapfooter">
                                            <span class="post-date">{{ object.published_at }}</span><span class="dot"></span><span class="post-read">{{ object.read_time }}</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                </div>
        </div>
    {% endfor %}
</div>
</section>
{% endblock content %}

diary/templates/stories/story_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block PageTitle %}
  {{ object.title }} -- {{ block.super }}
{% endblock PageTitle %}

{% block styles %}
  {{ block.super }}
  <style>
    .story img {
      max-width: 100%
    }
  </style>
{% endblock styles %}

{% block content %}
<div class='story'>
    <h1 class='title'>{{ object.title }}</h1>
    <h2 class='tagline'>{{ object.tagline }}</h2>
    <h4 class='written-by'>{% trans "Written by"%} <a href='{% url 'authors:detail' pk=object.author.id %}'>{{ object.author }}</a></h4>
    <h5 class='published-at'>{% trans "Published" %} {{ object.published_at }}</h5>

    {% if object.preceded_by %}
      <div class='previous-chapter'>
        {% trans "This story is the continuation of:" %} {% include "stories/partials/read_story_link.html" with story=object.preceded_by %}
      </div>
    {% endif %}

    <div class='story-markdown'>
      {{ object.html }}
    </div>

    {% if object.author.user == request.user %}
        <a href="{% url 'stories:edit' pk=object.id %}" class="btn btn-info" role="button">{% trans "Edit this story" %}</a>
        {% if not object.next_chapter %}
          <a href="{% url 'stories:create'%}?preceded_by={{object.id}}" class="btn btn-info" role="button">{% trans "Add another chapter?" %}</a>
        {% endif %}
    {% endif %}
</div>

{% if object.next_chapter %}
  <div class='next-chapter'>{% trans "Read more of this story: "%} {% include "stories/partials/read_story_link.html" with story=object.next_chapter %}</div>
{% endif %}


{% if object.inspired_by %}
  <div class='inspired-by'>
    {% trans "This story was inspired by:" %} {% include "stories/partials/read_story_link.html" with story=object.inspired_by %}
  </div>
{% endif %}


<div class="inspire" style="font-size:150%; margin-top:2em;">
  <a href="{% url 'stories:create' %}?inspired_by={{ object.id }}">
    {% trans "Want to share a story inspired by this?" %}
    <button type="button" class="btn btn-primary">Yes!</button>
  </a>
</div>

{% if inspired.exists %}
  <div class='inspired'>
    This story inspired these stories:
    <ul class='inspired'>
      {% for story in inspired %}
        <li class='inspired'>
          {% include "stories/partials/read_story_link.html" with story=story %}
        </li>
      {% endfor %}
      </ul>
  </div>
{% endif %}

{% endblock content %}

diary/templates/stories/story_form.html
{% extends "base.html" %}
{% load i18n %}

{% block PageTitle %}
  {% trans "Edit Story" as title_edit %}
  {% trans "Create New Story" as title_create %}
  {% if object.id %}{{ title_edit }}{% else %}{{ title_create }}{% endif %} -- {{ block.super }}
{% endblock PageTitle %}

{% block styles %}
  {{ block.super }}
  {# Hide the toolbar on small screens #}
  <style>
    div.ui.right.floated.item.martor-toolbar {
      display:none;
    }
    @media only screen and (min-width: 800px) {
      div.ui.right.floated.item.martor-toolbar {
        display: flex;
      }
    }
  </style>
{% endblock styles %}

{% block content %}
<div style="height: 51px"></div>
<form action="" method="post">
  {% csrf_token %}
  <fieldset>
  {% trans "Edit Story" as title_edit %}
  {% trans "Create New Story" as title_create %}
    <legend>{% if object.id %}{{ title_edit }}{% else %}{{ title_create }}{% endif %}</legend>
    {{ form.non_field_errors }}
    {% for field in form %}
      {{ field.errors }}
      {# Displaying checkboxes differently #}
      {% if field.name == 'preceded_by' %}
        <p class="checkbox">
          <label for="id_{{ field.name }}">{{ field }} {{ field.label }} <span class='preceded-by-title'>{{ preceded_by.full_title }}</span></label>
        </p>
      {% elif field.name == 'inspired_by' %}
        <p class="checkbox">
          <label for="id_{{ field.name }}">{{ field }} {{ field.label }} <span class='inspired-by-title'>{{ inspired_by.full_title }}</span></label>
        </p>
      {% else %}
        <p>
          {{ field.label_tag }}
          {{ field }}
        </p>
      {% endif %}
    {% endfor %}
  </fieldset>
  <input type="submit" value="{% trans "Save"%}" class="btn btn-info"/>
</form>
{% endblock content %}

{% block javascript %}
    {{ block.super }}
    {{ form.media }}
{% endblock javascript %}

diary/templates/stories/story_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Begin Featured ==================================================>
<section class="featured-posts">
<div class="section-title">
    <h2><span>Featured</span></h2>
</div>
-->
<div class="card-columns listfeaturedtag">

    {% for object in object_list|slice:":20" %}
        <!-- begin post -->
        <div class="card">
            <div class="row">
                <div class="col-md-12">
                    <div class="card-block">
                        <a href="{% url "stories:read" pk=object.pk %}" class='wrap-card-story'>
                            <h2 class="card-title">{{ object.full_title }}</h2>
                        </a>
                        <h4 class="card-text">{{ object.teaser|truncatechars_html:150 }}</h4>
                    </div>
                </div>
            </div>
            <div class="metafooter">
                <div class="wrapfooter">
                    <span class="meta-footer-thumb">
                        <a href="{% url 'stories:list-by-author' pk=object.author.pk %}"><img class="author-thumb" src="https://www.gravatar.com/avatar/e56154546cf4be74e393c62d1ae9f9d4?s=250&amp;d=mm&amp;r=x" alt="Sal"></a>
                    </span>
                    <span class="author-meta">
                        <span class="post-name"><a href="{% url 'stories:list-by-author' pk=object.author.pk %}">{{ object.author }}</a></span><br/>
                        <span class="post-date">{{ object.published_at }}</span><span class="dot"></span><span class="post-read">{{ object.read_time }}</span>
                    </span>
                    <span class="post-read-more"><a href="{% url "stories:read" pk=object.pk %}" title="Read Story"><svg class="svgIcon-use" width="25" height="25" viewbox="0 0 25 25"><path d="M19 6c0-1.1-.9-2-2-2H8c-1.1 0-2 .9-2 2v14.66h.012c.01.103.045.204.12.285a.5.5 0 0 0 .706.03L12.5 16.85l5.662 4.126a.508.508 0 0 0 .708-.03.5.5 0 0 0 .118-.285H19V6zm-6.838 9.97L7 19.636V6c0-.55.45-1 1-1h9c.55 0 1 .45 1 1v13.637l-5.162-3.668a.49.49 0 0 0-.676 0z" fill-rule="evenodd"></path></svg></a></span>
                </div>
            </div>
        </div>
    {% endfor %}

</div>
</section>

{% endblock content %}