diary/api/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework.authtoken import views as authtoken_views
from api import views

router = routers.DefaultRouter()
router.register(r'stories', views.StoryViewSet)
router.register(r'summaries', views.StorySummaryViewSet, basename='story-summary')
router.register(r'authors', views.AuthorViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('auth/api-token/', authtoken_views.obtain_auth_token, name='api-token'),
    path('auth/register/', views.create_user, name='api-register-user'),
    path('auth/', include('rest_framework.urls', namespace='rest_framework')),
]

diary/authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'
urlpatterns = [
    path('my-pseudonyms/', views.MyPseudonyms.as_view(), name='my-pseudonyms'),
    path('create/', views.Create.as_view(), name='create'),
    path('explain/', views.Explain.as_view(), name='explain'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),
]

diary/diary/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name="teaser.html")),
    path('admin/', admin.site.urls),
    path('stories/', include('stories.urls')),
    path('licenses/', include('licenses.urls')),
    path('martor/', include('martor.urls')),
    path('accounts/', include('userena.urls')),
    path('authors/', include('authors.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

diary/stories/urls.py
from django.urls import path
from . import views

app_name = 'stories'
urlpatterns = [
    path('', views.Recent.as_view(), name='recent'),
    path('list-by-author/<int:pk>/', views.ByAuthor.as_view(), name='list-by-author'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('create/', views.Create.as_view(), name='create'),
    path('read/<int:pk>/', views.Read.as_view(), name='read'),
]

diary/authors/models.py
from django.conf import settings
from django.db import models
from django.utils.safestring import SafeString

from martor.models import MartorField
from stories.utils import markdownify

# Create your models here.

class AuthorQuerySet(models.QuerySet):
    pass


class AuthorManager(models.Manager):

    def get_queryset(self):
        return AuthorQuerySet(self.model, using=self._db)

    def for_user(self, user):
        qset = self.get_queryset()
        return qset.filter(user=user).order_by('name')


class Author(models.Model):

    # A User can have multiple author roles (or pseudonyms)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             blank=False, null=False)

    name = models.CharField(max_length=64, blank=False, null=False, unique=True)

    # Each user profile will have a field where they can tell other users
    #   something about themselves. This field will be empty when the user
    #   creates their account, so we specify `blank=True`.
    bio_text = MartorField(blank=True)

    # In addition to the `bio` field, each user may have a profile image or
    #   avatar. Similar to `bio`, this field is not required. It may be blank.
    avatar = models.URLField(blank=True)

    objects = AuthorManager()

    def __str__(self):
        return self.name

    def bio_html(self):
        """ Return the markdownified biography of this author """
        return SafeString(markdownify(self.bio_text))

diary/authors/forms.py
from django import forms
from django.utils import timezone
from django.utils.translation import gettext as _

from martor.fields import MartorFormField

from authors.models import Author

class AuthorForm(forms.ModelForm):
    """ Used to create or edit a story.  It picks up on inspired_by via 2 mechanisms """

    bio_text = MartorFormField(label=_('Biography'), required=False)

    class Meta:
        model = Author
        fields = ['name', 'bio_text', 'avatar']

    def __init__(self, *args, user, **kwargs):
        super(AuthorForm, self).__init__(*args, **kwargs)

        width = Author._meta.get_field('name').max_length
        self.fields['name'].widget.attrs['size'] = width
        self.fields['bio_text'].widget.attrs['cols'] = width

        self.user = user


    def save(self, commit=True):
        """ Add the user to the object before we persist it """
        obj = super(AuthorForm, self).save(commit=False)
        obj.user = self.user

        if commit:
            obj.save()
            self.save_m2m()
        return obj

diary/authors/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, CreateView, ModelFormMixin
from django.urls import reverse

from authors.models import Author
from authors.forms import AuthorForm
from stories.models import Story

# Create your views here.

class MyPseudonyms(LoginRequiredMixin, ListView):

    def get_queryset(self):
        return Author.objects.for_user(self.request.user)

class CommonAuthorFormMixin(ModelFormMixin):
    model = Author
    form_class = AuthorForm

    def get_form_kwargs(self):
        """ The form needs the user to save an author object """
        kwargs = super(CommonAuthorFormMixin, self).get_form_kwargs()
        kwargs['user'] = self.request.user

        return kwargs

    def get_success_url(self):
        return reverse('authors:detail', kwargs={'pk': self.object.id})


class Explain(LoginRequiredMixin, CommonAuthorFormMixin, CreateView):
    """ Explain the concept of Pseudonyms and writing a story and get the user to
          create their first pseudonym so they can write a story. """
    template_name = "authors/explain_author_form.html"

    def get_success_url(self):
        return (self.request.GET.get('next', None)
                or super(Explain, self).get_success_url())

class Create(LoginRequiredMixin, CommonAuthorFormMixin, CreateView):
    """ Create a new author bio/name/avatar """
    pass


class Edit(LoginRequiredMixin, CommonAuthorFormMixin, UpdateView):
    """ Update an existing author bio/name/avatar """
    pass


class Detail(DetailView):
    model = Author

    def get_context_data(self, **kwargs):
        context = super(Detail, self).get_context_data(**kwargs)
        context['stories_by_author'] = Story.objects.by_author(author=self.object)

        return context

diary/templates/authors/author_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block PageTitle %}
  {{ object.name }} -- {{ block.super }}
{% endblock PageTitle %}

{% block content %}
<div class='story'>
    <h1>{{ object.name }}</h1>

    <div class='markdown biography'>
        {{ object.bio_html }}
    </div>

    {% if object.user == request.user %}
        <a href="{% url 'authors:edit' pk=object.id %}" class="btn btn-info" role="button">{% trans "Edit this Pseudonym" %}</a>
        <a href="{% url 'authors:my-pseudonyms' %}" class="btn btn-info" role="button">{% trans "My Pseudonyms" %}</a>
    {% endif %}
</div>
<h4>Stories by {{ object.name }}</h4>
<ul class='story-list'>
    {% for story in stories_by_author %}
        <li>
            {% include "stories/partials/read_story_link.html" with story=story %}
        </li>
    {% empty %}
        <li class='story'>{% trans "No stories :-(" %}</li>
    {% endfor %}
    <a href="{% url 'stories:create' %}?author={{ object.id }}" class="btn btn-info" role="button">{% trans "Write a new story" %}</a>
</ul>

{% endblock content %}

diary/templates/authors/author_form.html
{% extends "base.html" %}
{% load i18n %}

{% block PageTitle %}
  {% trans "Edit Pseudonym" as title_edit %}
  {% trans "Create New Pseudonym" as title_create %}
  {% if object.id %}{{ title_edit }}{% else %}{{ title_create }}{% endif %} -- {{ block.super }}
{% endblock PageTitle %}

{% block styles %}
  {{ block.super }}
  {# Hide the toolbar on small screens #}
  <style>
    div.ui.right.floated.item.martor-toolbar {
      display:none;
    }
    @media only screen and (min-width: 800px) {
      div.ui.right.floated.item.martor-toolbar {
        display: flex;
      }
    }
  </style>
{% endblock styles %}

{% block content %}
  <div style="height: 55px"></div>
  <p>A Pseudonym is a handle you can use when writing.  Maybe you have different writing styles, maybe
  you don't want to write about pain or something embarassing without a little anonymity.  We will
  know who you are and all of your writings can be clustered (under a pseudonym) but we won't connect
  your user/login to your pseudonyms.</p>

  <form action="" method="post">
    {% csrf_token %}
    <fieldset>
    {% trans "Edit Pseudonym" as title_edit %}
    {% trans "Create New Pseudonym" as title_create %}
      <legend>{% if object.id %}{{ title_edit }}{% else %}{{ title_create }}{% endif %}</legend>
      {{ form.non_field_errors }}
      {% for field in form %}
        {{ field.errors }}
        <p>
          {% if field.name == 'bio_text' %}
            <div>This is where you can give a little background for the pseudonym.  Maybe you are
            sharing stories your Grandmother told you and you want your audience to understand
            her better.  This is where you could share the background that would be common to all the
            writings by this author.</div>
          {% endif %}
          {{ field.label_tag }}
          {{ field }}
        </p>
      {% endfor %}
    </fieldset>
    <input type="submit" value="{% trans "Save"%}" class="btn btn-info"/>
  </form>
{% endblock content %}

{% block javascript %}
    {{ block.super }}
    {{ form.media }}
{% endblock javascript %}

diary/templates/authors/author_list.html
{% extends "userena/base_userena.html" %}
{% load static %}
{% load i18n %}

{% block profile-pseudonyms %}active{% endblock %}

{% block panel %}
<h2>Your Pseudonyms are</h2>

<ul class='my-pseudonyms'>
    {% for author in object_list %}
        <li class='pseudonym'><a href='{% url "authors:edit" author.id %}'>{{ author.name }}</a> - <span class='bio'>{{ author.bio_html|truncatechars_html:150 }}</span></li>
    {% empty %}
        <li class='no-pseudonyms'>{% trans 'You have no Pseudonyms' %}</li>
    {% endfor %}
        <li><a href="{% url 'authors:create' %}">{% trans 'Add a new Pseudonym' %}</a></li>
</ul>
{% endblock panel %}

diary/templates/authors/explain_author_form.html
{% extends "authors/author_form.html" %}
{% load i18n %}

{% block content %}
  <div style="height: 55px"></div>

  <h3>{% trans 'It looks like this is your first story!  Glad you could join us.' %}</h3>
  <p>{% trans "Before you can create a story, you need to create a Pseudonym, the name this story will be published under." %}</p>

  {{ block.super }}
{% endblock content %}

{% block javascript %}
    {{ block.super }}
    {{ form.media }}
{% endblock javascript %}