diary/api/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework.authtoken import views as authtoken_views
from api import views

router = routers.DefaultRouter()
router.register(r'stories', views.StoryViewSet)
router.register(r'summaries', views.StorySummaryViewSet, basename='story-summary')
router.register(r'authors', views.AuthorViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('auth/api-token/', authtoken_views.obtain_auth_token, name='api-token'),
    path('auth/register/', views.create_user, name='api-register-user'),
    path('auth/', include('rest_framework.urls', namespace='rest_framework')),
]

diary/diary/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name="teaser.html")),
    path('admin/', admin.site.urls),
    path('stories/', include('stories.urls')),
    path('licenses/', include('licenses.urls')),
    path('martor/', include('martor.urls')),
    path('accounts/', include('userena.urls')),
    path('authors/', include('authors.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

diary/entries/urls.py
from django.urls import path
from . import views

app_name = 'entries'
urlpatterns = [
    path('', views.Recent.as_view(), name='recent'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('create/', views.Create.as_view(), name='create'),
    path('read/<int:pk>/', views.Read.as_view(), name='read'),
]

diary/entries/templates/entries/entry_detail.html
{% extends "base.html" %}

{% block contents %}

    <h1>{{ object.title }}</h1>

    <div class='markdown'>
    {{ formatted_text }}
    </div>

    {% if object.author.user == request.user %}
        <a href="{% url 'entries:edit' pk=object.id %}">Edit</a>
    {% endif %}

<div class="inspire" style="font-size:150%; margin-top:2em;">
Did this touch or inspire you?  Would you like to share a story from your life?
</div>

{% endblock contents %}

diary/entries/templates/entries/entry_form.html
{% extends "base.html" %}

{% block contents %}


<form method="POST" action="">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

{{ form.media }}

{% endblock contents %}