diary/api/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework.authtoken import views as authtoken_views
from api import views

router = routers.DefaultRouter()
router.register(r'stories', views.StoryViewSet)
router.register(r'summaries', views.StorySummaryViewSet, basename='story-summary')
router.register(r'authors', views.AuthorViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('auth/api-token/', authtoken_views.obtain_auth_token, name='api-token'),
    path('auth/register/', views.create_user, name='api-register-user'),
    path('auth/', include('rest_framework.urls', namespace='rest_framework')),
]

diary/diary/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name="teaser.html")),
    path('admin/', admin.site.urls),
    path('stories/', include('stories.urls')),
    path('licenses/', include('licenses.urls')),
    path('martor/', include('martor.urls')),
    path('accounts/', include('userena.urls')),
    path('authors/', include('authors.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

diary/stories/urls.py
from django.urls import path
from . import views

app_name = 'stories'
urlpatterns = [
    path('', views.Recent.as_view(), name='recent'),
    path('list-by-author/<int:pk>/', views.ByAuthor.as_view(), name='list-by-author'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('create/', views.Create.as_view(), name='create'),
    path('read/<int:pk>/', views.Read.as_view(), name='read'),
]

diary/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="icon" href="{% static 'img/favicon.ico' %}">
	<title>{% block PageTitle %}Diary of Life{% endblock PageTitle %}</title>
	<!-- Bootstrap core CSS -->
	<link href="{% static 'css/Semantic/semantic.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<!-- Fonts -->
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
	<!-- Custom styles for this template -->
	<link href="{% static 'css/sitestyles.3.css' %}" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Special+Elite" rel="stylesheet">  </head>
	{% block styles %}
	<style>
		input {
			max-width: 100%
		}
	</style>
	{% endblock styles %}
</head>
<body>

<nav class="navbar navbar-toggleable-md navbar-light bg-white fixed-top mediumnavigation">
<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<!-- Begin Logo -->
<a class="navbar-brand" href="{% url 'stories:recent' %}">
	<img src="{% static 'img/logo.png' %}" alt="logo">
</a>
<div class="collapse navbar-collapse" id="navbarsExampleDefault">
	{% block top-menu %}
	<ul class="navbar-nav ml-auto">
		<li class="nav-item">
			<a class="nav-link" href="{% url 'stories:recent' %}">Stories</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="{% url 'stories:create' %}">Post</a>
		</li>
		{% if user.is_authenticated %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'userena_signout' %}">Signout</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'userena_profile_detail' user.username %}">Profile</a>
			</li>
		{% else %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'userena_signin' %}">Signup/Signin</a>
			</li>
		{% endif %}
	</ul>
	{% endblock top-menu %}
	{% block search %}
	<form class="form-inline my-2 my-lg-0">
		<input class="form-control mr-sm-2" type="text" placeholder="Search">
		<span class="search-icon"><svg class="svgIcon-use" width="25" height="25" viewbox="0 0 25 25"><path d="M20.067 18.933l-4.157-4.157a6 6 0 1 0-.884.884l4.157 4.157a.624.624 0 1 0 .884-.884zM6.5 11c0-2.62 2.13-4.75 4.75-4.75S16 8.38 16 11s-2.13 4.75-4.75 4.75S6.5 13.62 6.5 11z"></path></svg></span>
	</form>
	{% endblock search %}
</div>
</nav>
<!-- End Nav ================================================== -->

<div class="container">
{% block site-title %}
	<!--
	<div class="mainheading">
		<h1 class="sitetitle">Diary Of Life</h1>
			<p class="lead">
			Stories of life that connect us all
				</p>
			</div>
		-->
	{% endblock site-title %}

{% block content %}
{% endblock content %}


{% block footer %}
	<!-- <div class="footer">
	<p class="pull-left">
		Copyright &copy; 2019 Diary of Life
			</p>
		<div class="clearfix">
		</div>
		</div> -->
	{% endblock footer %}

</div>
<!-- /.container -->

{% block javascript %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
{% endblock javascript %}
</body>
</html>

diary/templates/teaser.html
{% extends "base.html" %}

{% block top-menu %}
{% endblock top-menu %}

{% block search %}
{% endblock search %}

{% block styles %}
<style>
.long-explanation {
    margin: 1em;
    color: #8a2ea8;
    font-size: 120%;
}
</style>
{% endblock styles %}

{% block content %}

<h3>Collaborative Storytelling</h3>
<div class='long-explanation'>
Civilization is built out of stories: mine, yours, his, hers.  When we share our stories, our hopes
our fears, we have a better chance of understanding each other, of become more integrated and less
separated.</div>

<div class='long-explanation'>
I hope you will enjoy the stories you read here and most importantly,
I hope this site will inspire you to share your stories.  Happy stories, sad stories, stories you've
heard.
</div>

<div class='long-explanation'>
In order to encourage sharing of more personal stories, we have the concept of Pseudonyms.  With
these pseudonyms, you can share stories that you might not want to publicly admit to, but sometimes
sharing our stories helps us put them in perspective and helps us find comfort as we learn that
others have problems very similar to ours.
</div>

<h3>Without Comments</h3>
<div class='long-explanation'>
Too often people listen, not to understand, but to respond.  We don't want that here.  We want
understanding.  So if a particular story moves you to express yourself, do it as a story inspired by
another story.  There won't be any back and forth in the comment section to take away from the story.
</div>

<div class='long-explanation'>
Too often you see comments on YouTube videos or Facebook posts that look just like drive by
shootings.  Where the hate and the division take over and all valuable discourse is just buried in
noise we decided to forgo comments so we don't have to worry about that.
</div>

<h3>
    TL;DR
</h3>
<div class='long-explanation'>
 <a href="{% url 'stories:recent' %}">Show me some stories already!</a>
</div>

{% endblock content %}